// export const GET_ERROR_DETAILS = 'GET_ERROR_DETAILS';
export const SET_USER = 'SET_USER'
export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS'
export const SET_LOGGEDIN_USER = 'SET_LOGGEDIN_USER'
export const SET_LOGIN_TYPE = 'SET_LOGIN_TYPE'
export const SET_LOGGEDIN_USER_TYPE = 'SET_LOGGEDIN_USER_TYPE'
