import { ADMIN_FETCH_HOTEL, ADMIN_HOTEL_TOGGLE, ADMIN_FETCH_HOTEL_BY_ID, ADMIN_HOTEL_COUNT, ADMIN_HOTEL_APPROVE, ADMIN_HOTEL_CREATE, ADMIN_HOTEL_UPDATE, ADMIN_FETCH_HOTEL_COUNT, ADMIN_FETCH_PROPERTIES_PAGINATION } from './hotels'
import { ADMIN_FETCH_BOOKING, ADMIN_BOOKING_APPROVE, ADMIN_FETCH_COMPLETED_BOOKING, ADMIN_FETCH_CANCELLED_BOOKING, ADMIN_FETCH_PENDING_BOOKING, AGENT_FETCH_BOOKING, ADMIN_FETCH_BOOKING_PAGINATION } from './booking'
import {
  ADMIN_FETCH_USERS, ADMIN_USER_APPROVE,
  ADMIN_USER_TOGGLE,
  ADMIN_USER_DELETE,
  ADMIN_SAVE,
  ADMIN_UPDATE,
  ADMIN_FETCH_BY_ID,
  ADMIN_FETCH_CUSTOMERS,
  ADMIN_FETCH_HOTEL_USER,
  ADMIN_FETCH_ADMIN_USER_PAGINATION,
  ADMIN_FETCH_CUSTOMER_PAGINATION,
  ADMIN_FETCH_SUBSCRIBE_PAGINATION,
  ADMIN_USER_ACTIVE_DEACTIVE
} from './users'

import {
  ADMIN_BLOG_FETCH_ALL,
  ADMIN_BLOG_FETCH_BY_ID,
  ADMIN_BLOG_CREARTE,
  ADMIN_BLOG_UPDATE,
  ADMIN_BLOG_DELTE,
  ADMIN_FETCH_ALL_CONTENT,
  ADMIN_FETCH_CONTACT_PAGINATION,
  ADMIN_FETCH_BLOG_PAGINATION
} from './blog'

export {
  ADMIN_FETCH_HOTEL,
  ADMIN_FETCH_HOTEL_BY_ID,
  ADMIN_HOTEL_APPROVE,
  ADMIN_HOTEL_CREATE,
  ADMIN_HOTEL_UPDATE,
  ADMIN_FETCH_BOOKING,
  ADMIN_FETCH_USERS,
  ADMIN_HOTEL_TOGGLE,
  ADMIN_USER_APPROVE,
  ADMIN_USER_TOGGLE,
  ADMIN_HOTEL_COUNT,
  // blog
  ADMIN_BLOG_FETCH_ALL,
  ADMIN_BLOG_FETCH_BY_ID,
  ADMIN_BLOG_CREARTE,
  ADMIN_BLOG_UPDATE,
  ADMIN_BLOG_DELTE,
  ADMIN_USER_DELETE,
  ADMIN_SAVE,
  ADMIN_UPDATE,
  ADMIN_FETCH_BY_ID,
  ADMIN_BOOKING_APPROVE,
  ADMIN_FETCH_CUSTOMERS,
  ADMIN_FETCH_HOTEL_USER,
  ADMIN_FETCH_COMPLETED_BOOKING,
  ADMIN_FETCH_CANCELLED_BOOKING,
  ADMIN_FETCH_PENDING_BOOKING,
  ADMIN_FETCH_ALL_CONTENT,
  ADMIN_FETCH_HOTEL_COUNT,
  AGENT_FETCH_BOOKING,
  ADMIN_FETCH_PROPERTIES_PAGINATION,
  ADMIN_FETCH_BOOKING_PAGINATION,
  ADMIN_FETCH_ADMIN_USER_PAGINATION,
  ADMIN_FETCH_CUSTOMER_PAGINATION,
  ADMIN_FETCH_SUBSCRIBE_PAGINATION,
  ADMIN_USER_ACTIVE_DEACTIVE,
  ADMIN_FETCH_CONTACT_PAGINATION,
  ADMIN_FETCH_BLOG_PAGINATION
}
